# Streamlit Cloud Secrets (TOML format)
# Copy this content to your Streamlit Cloud app settings > Secrets

OPENAI_API_KEY = ""
USER_AGENT = "myagent"
PG_DB_NAME = "postgres"
PG_USER = "postgres"
PG_PASSWORD = "<YOUR_POSTGRES_PASSWORD>"
PG_HOST = "localhost"
PG_PORT = "5433"
PG_DB_URL = "postgresql://<YOUR_POSTGRES_USER>:<YOUR_POSTGRES_PASSWORD>@localhost:5433/<YOUR_POSTGRES_DB_NAME>"
GEMINI_API_KEY = "AIzaSyCPC6pPCr4CEIh6H-2EHhzkO7CcLTnWzzo"
GOOGLE_API_KEY = "AIzaSyCPC6pPCr4CEIh6H-2EHhzkO7CcLTnWzzo"
AUTHORIZE_URL = "https://accounts.google.com/o/oauth2/auth"
TOKEN_URL = "https://oauth2.googleapis.com/token"
CLIENT_ID = ""
CLIENT_SECRET = ""
REDIRECT_URI = "http://localhost:8501"
